<?php
/**
* views template to output one 'row' of a view.
* This code was generated by the views theming wizard
* Date: ---, --/--/----, --:-- --
* View: frontpage
*
* Variables available:
* $view -- the entire view object. Important parts of this object are
*   frontpage, .
* $view_type -- The type of the view. Probably 'page' or 'block' but could
*   also be 'embed' or other string passed in from a custom view creator.
* $node -- the raw data. This is not a real node object, but will contain
*   the nid as well as other support fields that might be necessary.
* $count -- the current row in the view (not TOTAL but for this page) starting
*   from 0.
* $stripe -- 'odd' or 'even', alternating. * $nid -- Display the NID of a node.
* $nid_label -- The assigned label for $nid
*
* This function goes in your views-list-frontpage.tpl.php file
*/

//$node = node_load($node->nid);
//print_r($view);die();

//now we add the stylesheet...
//  drupal_add_css(path_to_theme() .'/views-list-video_jukebox.css');
//  drupal_add_js(path_to_theme() .'/scripts/scriptaculous.js');
//  drupal_add_js(path_to_theme() .'/scripts/prototype.js');
//[preview] =&gt; files/images/Alfre.Woodard.Truth.flv.thumb.preview.jpg
//[thumbnail] =&gt; files/images/Alfre.Woodard.Truth.flv.thumb.thumbnail.jpg
//[_original] =&gt; files/images/Alfre.Woodard.Truth.flv.thumb.jpg
//[video_thumbnail] =&gt; files/images/Alfre.Woodard.Truth.flv.thumb.video_thumbnail.jpg


 //print_r($video_node);die();
 //$profile_node =  node_load($node->field_profile_name[0]['nid']);


//		$video_link = $node->node_data_field_vimeo_link_field_vimeo_link_url;

 $img_node =node_load($node->node_data_field_thumb_nail_field_thumb_nail_nid);
 $video_node =node_load($node->nid);
		switch ($node->node_data_field_video_source_field_video_source_value)
		{
				case "vimeo":
				
						$swfSrc = explode("/",$node->node_data_field_vimeo_link_field_vimeo_link_url);
						$swfSrc = $swfSrc[count($swfSrc)-1];
						$swfSrc = 'http://www.vimeo.com/moogaloop.swf?clip_id='.$swfSrc.'&server=www.vimeo.com&show_title=0&show_byline=0&show_portrait=0&color=&fullscreen=1&autoplay=1';
						$video_link = $swfSrc ;
				
				break;

				case "youtube":

							$video_link = $node->node_data_field_youtube_link_field_youtube_link_url;
				break;
				case "local":
		
							$video_link = $node->node_data_field_local_src;
				break;
		}
	 ?>

	<a href="<?php print $video_link?>" rel="lightvideo[width:640px; height:360px;][<?php print $node->title?>]">
		<img src="<?php echo $asset_path."/".VIDEO_PLAY_BUTTON_IMAGE_SRC; ?>" class="video-play-button"/>
		<img src='/<?php echo $img_node->images['video_thumbnail']; ?>' alt=''/>
	</a>
</td> 


<td class="video-list-text">
	<!-- video title  -->  	
<!--	<h3 class="video-list title"><a href="http://video.google.com/videoplay?docid=1811233136844420765" rel="lightvideo[width:400px; height:300px;][This is a caption]"><?php print($node->node_title)  ?></a></h3>  	
-->	
		<h3 class="video-list title"><a href="<?php print $video_link?>" rel="lightvideo[width:640px; height:360px;][<?php print $node->title?>]"><?php print($node->node_title)  ?></a></h3> 
	<div class="viewVideo">
		<?php echo t($video_node->body); ?>
		<!--<a href="<?php echo '/node/'.$node->nid; ?>" >watch the video &#8250;</a>-->
		
		
<div class="view-field view-data-field-video-source-value">
	 <a href="<?php print $video_link?>" rel="lightvideo[width:640px; height:360px;][<?php print $node->title?>]">watch this video &rsaquo;</a>
	 <?php echo admin_edit_content($node->nid,$administrator) ?>
</div>

	</div>
</td>
</tr>
 
 
 