<?php /* Smarty version 2.6.14, created on 2010-04-29 13:57:16
         compiled from CRM/Contact/Page/View/UserDashBoard/Participant.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'ts', 'CRM/Contact/Page/View/UserDashBoard/Participant.tpl', 5, false),array('function', 'counter', 'CRM/Contact/Page/View/UserDashBoard/Participant.tpl', 13, false),array('function', 'cycle', 'CRM/Contact/Page/View/UserDashBoard/Participant.tpl', 15, false),array('function', 'crmURL', 'CRM/Contact/Page/View/UserDashBoard/Participant.tpl', 16, false),array('modifier', 'crmDate', 'CRM/Contact/Page/View/UserDashBoard/Participant.tpl', 18, false),array('modifier', 'date_format', 'CRM/Contact/Page/View/UserDashBoard/Participant.tpl', 22, false),array('modifier', 'truncate', 'CRM/Contact/Page/View/UserDashBoard/Participant.tpl', 29, false),)), $this); ?>
<div class="view-content">
<?php if ($this->_tpl_vars['event_rows']): ?>
  <?php echo '<div class="description">';  $this->_tag_stack[] = array('ts', array()); $_block_repeat=true;smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start();  echo 'Click on the event name for more information.';  $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack);  echo '</div><table class="selector"><tr class="columnheader"><th>';  $this->_tag_stack[] = array('ts', array()); $_block_repeat=true;smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start();  echo 'Event';  $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack);  echo '</th><th>';  $this->_tag_stack[] = array('ts', array()); $_block_repeat=true;smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start();  echo 'Event Date(s)';  $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack);  echo '</th><th>';  $this->_tag_stack[] = array('ts', array()); $_block_repeat=true;smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start();  echo 'Status';  $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack);  echo '</th></tr>';  echo smarty_function_counter(array('start' => 0,'skip' => 1,'print' => false), $this); echo '';  $_from = $this->_tpl_vars['event_rows']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['row']):
 echo '<tr id=\'rowid';  echo $this->_tpl_vars['row']['participant_id'];  echo '\' class="';  echo smarty_function_cycle(array('values' => "odd-row,even-row"), $this); echo '';  if ($this->_tpl_vars['row']['status'] == Cancelled):  echo ' disabled';  endif;  echo '"><td><a href="';  echo CRM_Utils_System::crmURL(array('p' => 'civicrm/event/info','q' => "reset=1&id=".($this->_tpl_vars['row']['event_id'])."&context=dashboard"), $this); echo '">';  echo $this->_tpl_vars['row']['event_title'];  echo '</a></td><td>';  echo ((is_array($_tmp=$this->_tpl_vars['row']['event_start_date'])) ? $this->_run_mod_handler('crmDate', true, $_tmp) : smarty_modifier_crmDate($_tmp));  echo '';  if ($this->_tpl_vars['row']['event_end_date']):  echo '&nbsp; - &nbsp;';  echo '';  if (((is_array($_tmp=$this->_tpl_vars['row']['event_end_date'])) ? $this->_run_mod_handler('date_format', true, $_tmp, "%Y%m%d") : smarty_modifier_date_format($_tmp, "%Y%m%d")) == ((is_array($_tmp=$this->_tpl_vars['row']['event_start_date'])) ? $this->_run_mod_handler('date_format', true, $_tmp, "%Y%m%d") : smarty_modifier_date_format($_tmp, "%Y%m%d"))):  echo '';  echo ((is_array($_tmp=$this->_tpl_vars['row']['event_end_date'])) ? $this->_run_mod_handler('date_format', true, $_tmp, "%I:%M %p") : smarty_modifier_date_format($_tmp, "%I:%M %p"));  echo '';  else:  echo '';  echo ((is_array($_tmp=$this->_tpl_vars['row']['event_end_date'])) ? $this->_run_mod_handler('crmDate', true, $_tmp) : smarty_modifier_crmDate($_tmp));  echo '';  endif;  echo '';  endif;  echo '</td><td>';  echo $this->_tpl_vars['row']['status'];  echo '<br/>';  echo ((is_array($_tmp=((is_array($_tmp=$this->_tpl_vars['row']['modified_date'])) ? $this->_run_mod_handler('truncate', true, $_tmp, 10, '') : smarty_modifier_truncate($_tmp, 10, '')))) ? $this->_run_mod_handler('crmDate', true, $_tmp) : smarty_modifier_crmDate($_tmp));  echo '</td></tr>';  endforeach; endif; unset($_from);  echo '</table>'; ?>

<?php else: ?>
   <div class="messages status">
       <dl>
         <dt><img src="<?php echo $this->_tpl_vars['config']->resourceBase; ?>
i/Inform.gif" alt="<?php $this->_tag_stack[] = array('ts', array()); $_block_repeat=true;smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>status<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>" /></dt>
           <dd>
               <?php $this->_tag_stack[] = array('ts', array()); $_block_repeat=true;smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>You are not registered for any current or upcoming Events.<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>
           </dd>
       </dl>
   </div>
<?php endif; ?>
</div>